#!/bin/bash
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd -P)"
CLAUDE_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
AGENTS_SKILLS="${AGENTS_SKILLS_DIR:-$HOME/.agents/skills}"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CHECK=0
case "${1:-}" in
  --check) CHECK=1 ;;
  '') ;;
  *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

conflicts=0
pending=0
. "$REPO/lib/links.sh"

generate_agents_md() {
  local target="$CODEX_HOME/AGENTS.md" rendered staged
  if [ ! -d "$CODEX_HOME" ]; then echo "  skip: $CODEX_HOME absent"; return 0; fi
  rendered="$(python3 "$REPO/scripts/render_agents_md.py" --claude-md "$REPO/claude/CLAUDE.md" --rules-dir "$REPO/claude/rules")"
  if [ -L "$target" ] || { [ -e "$target" ] && [ ! -f "$target" ]; }; then
    conflict "$target" "not generated by apply.sh"
    return 0
  fi
  if [ -f "$target" ]; then
    if [ "$(head -n 1 "$target")" != "$(printf '%s\n' "$rendered" | head -n 1)" ]; then
      conflict "$target" "not generated by apply.sh"
      return 0
    fi
    if printf '%s\n' "$rendered" | cmp -s - "$target"; then echo "  ok: $target"; return 0; fi
  fi
  echo "  generate: $target"
  pending=1
  [ "$CHECK" = 1 ] && return 0
  staged="$(mktemp "$CODEX_HOME/.AGENTS.md.XXXXXX")"
  printf '%s\n' "$rendered" > "$staged"
  mv "$staged" "$target"
}

link_target "$REPO/claude/CLAUDE.md" "$CLAUDE_HOME/CLAUDE.md"
for source in "$REPO"/claude/skills/*; do
  [ -d "$source" ] && link_target "$source" "$CLAUDE_HOME/skills/$(basename "$source")"
done
for source in "$REPO"/claude/skills/*; do
  [ -d "$source" ] && link_target "$source" "$AGENTS_SKILLS/$(basename "$source")"
done
for source in "$REPO"/claude/agents/*.md; do
  [ -f "$source" ] && link_target "$source" "$CLAUDE_HOME/agents/$(basename "$source")"
done
for source in "$REPO"/claude/rules/*.md; do
  [ -f "$source" ] && link_target "$source" "$CLAUDE_HOME/rules/$(basename "$source")"
done
for source in "$REPO"/claude/hooks/*; do
  [ -f "$source" ] && link_target "$source" "$CLAUDE_HOME/hooks/$(basename "$source")"
done

prune "$CLAUDE_HOME/CLAUDE.md" "$CLAUDE_HOME"/skills/* "$CLAUDE_HOME"/agents/* \
  "$CLAUDE_HOME"/rules/* "$CLAUDE_HOME"/hooks/* "$AGENTS_SKILLS"/*
report_foreign "$REPO/claude/skills" "$CLAUDE_HOME"/skills/*
report_foreign "$REPO/claude/agents" "$CLAUDE_HOME"/agents/*
report_foreign "$REPO/claude/rules" "$CLAUDE_HOME"/rules/*
report_foreign "$REPO/claude/hooks" "$CLAUDE_HOME"/hooks/*
report_foreign "$REPO/claude/skills" "$AGENTS_SKILLS"/*
generate_agents_md

settings_status=0
if [ "$CHECK" = 1 ]; then
  python3 "$REPO/scripts/merge_settings.py" --settings "$CLAUDE_HOME/settings.json" \
    --hooks-dir "$CLAUDE_HOME/hooks" --manifest "$REPO/claude/settings.json" --check \
    || settings_status=$?
  if [ "$pending" = 0 ] && [ "$conflicts" = 0 ] && [ "$settings_status" = 0 ]; then exit 0; fi
  exit 1
fi

python3 "$REPO/scripts/merge_settings.py" --settings "$CLAUDE_HOME/settings.json" \
  --hooks-dir "$CLAUDE_HOME/hooks" --manifest "$REPO/claude/settings.json" || settings_status=$?
if [ "$conflicts" = 0 ] && [ "$settings_status" = 0 ]; then
  echo "Applied. Restart Claude Code sessions to pick up changes."
  exit 0
fi
exit 1
