#!/bin/bash
set -u

SCRATCH=ai-config-test
. "$(dirname "$0")/lib.sh"

FIX="$WORK/repo"
mkdir -p "$FIX/claude/skills/demo" "$FIX/claude/agents" "$FIX/claude/rules" "$FIX/claude/hooks" "$FIX/scripts"
mkdir -p "$FIX/claude/rulesets/typescript" "$FIX/lib" "$FIX/bin"
cp "$HERE/../apply.sh" "$FIX/apply.sh"
cp "$HERE/../lib/links.sh" "$FIX/lib/links.sh"
cp "$HERE/../scripts/merge_settings.py" "$FIX/scripts/merge_settings.py"
cp "$HERE/../scripts/render_agents_md.py" "$FIX/scripts/render_agents_md.py"
echo "claude" > "$FIX/claude/CLAUDE.md"
echo "skill" > "$FIX/claude/skills/demo/SKILL.md"
echo "agent" > "$FIX/claude/agents/demo.md"
printf '%s\n' '# Demo' 'rule' > "$FIX/claude/rules/demo.md"
echo "plain rule" > "$FIX/claude/rules/plain.md"
printf '%s\n' '---' 'paths: ["**/*.ts"]' '---' '# Code style' 'typescript rule' > "$FIX/claude/rulesets/typescript/code-style.md"
echo "print('hook')" > "$FIX/claude/hooks/demo.py"
printf '%s\n' '#!/bin/bash' 'exit 0' > "$FIX/bin/second-opinion-codex"
printf '%s\n' '{"hooks": {"PreToolUse": [{"matcher": "Bash", "script": "demo.py", "timeout": 10}]},' \
  ' "defaults": {"attribution": {"commit": "", "pr": "", "sessionUrl": false},' \
  '  "permissions.allow": ["Bash(git commit:*)", "Bash(rm:*)", "Bash(find:*)", "Bash(mv:*)"],' \
  '  "permissions.ask": ["Bash(git push:*)"]}}' > "$FIX/claude/settings.json"

AGENTS_MD="$WORK/agents.expected"
printf '%s\n' '<!-- generated by ai-config apply.sh from claude/CLAUDE.md and claude/rules; edit those, not this file -->' \
  '' 'claude' '' '# Demo' 'rule' '' 'plain rule' > "$AGENTS_MD"

homes=0
fresh_home() {
  homes=$((homes + 1))
  HOME_DIR="$WORK/home$homes"
  AGENTS_DIR="$WORK/agents$homes"
  CODEX_DIR="$WORK/codex$homes"
  BIN_DIR="$WORK/bin$homes"
  mkdir -p "$CODEX_DIR"
}

OUT="$WORK/out"
ERR="$WORK/err"
RUN_PATH="$PATH"
run_apply() {
  CLAUDE_CONFIG_DIR="$HOME_DIR" AGENTS_SKILLS_DIR="$AGENTS_DIR" CODEX_HOME="$CODEX_DIR" \
    CLAUDE_LOCAL_BIN="$BIN_DIR" PATH="$RUN_PATH" \
    /bin/bash "$FIX/apply.sh" "$@" >"$OUT" 2>"$ERR"
  status=$?
}

all_linked() {
  links_to "$HOME_DIR/CLAUDE.md" "$FIX/claude/CLAUDE.md"; check $? "$1 links CLAUDE.md"
  links_to "$HOME_DIR/skills/demo" "$FIX/claude/skills/demo"; check $? "$1 links the skill into the claude home"
  links_to "$HOME_DIR/agents/demo.md" "$FIX/claude/agents/demo.md"; check $? "$1 links the agent"
  links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md"; check $? "$1 links the rule"
  links_to "$HOME_DIR/hooks/demo.py" "$FIX/claude/hooks/demo.py"; check $? "$1 links the hook"
  links_to "$AGENTS_DIR/demo" "$FIX/claude/skills/demo"; check $? "$1 links the skill into the agents skills dir"
  links_to "$BIN_DIR/second-opinion-codex" "$FIX/bin/second-opinion-codex"; check $? "$1 links the second-opinion script"
}

fresh_home
run_apply --check
[ "$status" = 1 ]; check $? "1 check on a nonexistent target exits 1"
[ ! -e "$HOME_DIR" ]; check $? "1 check leaves the claude home absent"
[ ! -L "$HOME_DIR" ]; check $? "1 check leaves no claude home symlink"
[ ! -e "$AGENTS_DIR" ]; check $? "1 check leaves the agents skills dir absent"
[ ! -e "$BIN_DIR" ]; check $? "1 check leaves the local bin dir absent"
[ -z "$(ls -A "$CODEX_DIR")" ]; check $? "1 check leaves CODEX_HOME empty"

run_apply
[ "$status" = 0 ]; check $? "2 fresh apply exits 0"
all_linked "2 fresh apply"
grep -q '^Applied\. Restart Claude Code sessions to pick up changes\.$' "$OUT"; check $? "2 fresh apply prints Applied"
python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
group = doc["hooks"]["PreToolUse"][0]
assert group["matcher"] == "Bash"
assert group["hooks"] == [{"type": "command", "command": "python3 " + sys.argv[2] + "/hooks/demo.py", "timeout": 10}]
assert doc["attribution"] == {"commit": "", "pr": "", "sessionUrl": False}
assert doc["permissions"] == {
    "allow": ["Bash(git commit:*)", "Bash(rm:*)", "Bash(find:*)", "Bash(mv:*)"],
    "ask": ["Bash(git push:*)"],
}
assert list(doc) == ["hooks", "attribution", "permissions"]
' "$HOME_DIR/settings.json" "$HOME_DIR"
check $? "2 fresh apply writes the demo hook and the defaults into settings.json"

cp "$HOME_DIR/settings.json" "$WORK/settings.before"
run_apply
[ "$status" = 0 ]; check $? "3 second apply exits 0"
! grep -Eq '^  (link|adopt|prune|foreign):' "$OUT"; check $? "3 second apply changes nothing"
[ "$(grep -c '^  ok: ' "$OUT")" = 9 ]; check $? "3 second apply prints ok for every target"
grep -q "^  ok: $HOME_DIR/CLAUDE.md -> $FIX/claude/CLAUDE.md$" "$OUT"; check $? "3 second apply prints ok for CLAUDE.md"
grep -q "^  ok: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT"; check $? "3 second apply prints ok for the skill"
cmp -s "$WORK/settings.before" "$HOME_DIR/settings.json"; check $? "3 second apply leaves settings.json byte-identical"

run_apply --check
[ "$status" = 0 ]; check $? "4 check after apply exits 0"

fresh_home
mkdir -p "$HOME_DIR/agents"
echo "different" > "$HOME_DIR/agents/demo.md"
run_apply
[ "$status" = 1 ]; check $? "5 differing regular file: apply exits 1"
grep -q "^CONFLICT: $HOME_DIR/agents/demo.md" "$ERR"; check $? "5 differing regular file is a CONFLICT"
! grep -q '^Applied\.' "$OUT"; check $? "5 differing regular file: apply prints no Applied line"
[ ! -L "$HOME_DIR/agents/demo.md" ]; check $? "5 differing regular file is left unlinked"
[ "$(cat "$HOME_DIR/agents/demo.md")" = "different" ]; check $? "5 differing regular file keeps its content"
links_to "$HOME_DIR/CLAUDE.md" "$FIX/claude/CLAUDE.md"; check $? "5 CLAUDE.md is linked despite the conflict"
links_to "$HOME_DIR/skills/demo" "$FIX/claude/skills/demo"; check $? "5 the skill is linked despite the conflict"
links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md"; check $? "5 the rule is linked despite the conflict"
links_to "$HOME_DIR/hooks/demo.py" "$FIX/claude/hooks/demo.py"; check $? "5 the hook is linked despite the conflict"

fresh_home
mkdir -p "$HOME_DIR/rules"
cp "$FIX/claude/rules/demo.md" "$HOME_DIR/rules/demo.md"
run_apply
[ "$status" = 0 ]; check $? "6 identical regular file: apply exits 0"
grep -q "^  adopt: $HOME_DIR/rules/demo.md -> $FIX/claude/rules/demo.md$" "$OUT"; check $? "6 identical regular file is reported adopted"
links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md"; check $? "6 identical regular file is adopted"

fresh_home
mkdir -p "$HOME_DIR/skills"
cp -R "$FIX/claude/skills/demo" "$HOME_DIR/skills/demo"
run_apply
[ "$status" = 0 ]; check $? "7 identical directory: apply exits 0"
grep -q "^  adopt: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT"; check $? "7 identical directory is reported adopted"
links_to "$HOME_DIR/skills/demo" "$FIX/claude/skills/demo"; check $? "7 identical directory is adopted"
[ ! -e "$FIX/claude/skills/demo/demo" ]; check $? "7 no demo link is nested inside the source skill"
[ ! -L "$FIX/claude/skills/demo/demo" ]; check $? "7 no link is nested inside the source skill"
[ "$(cat "$FIX/claude/skills/demo/SKILL.md")" = "skill" ]; check $? "7 the source skill keeps its content"

fresh_home
mkdir -p "$HOME_DIR/skills"
echo "x" > "$HOME_DIR/skills/demo"
run_apply
[ "$status" = 1 ]; check $? "8 regular file at a skill target: apply exits 1"
grep -q "^CONFLICT: $HOME_DIR/skills/demo" "$ERR"; check $? "8 regular file at a skill target is a CONFLICT"
[ ! -L "$HOME_DIR/skills/demo" ]; check $? "8 regular file at a skill target is left unlinked"
[ "$(cat "$HOME_DIR/skills/demo")" = "x" ]; check $? "8 regular file at a skill target keeps its content"

fresh_home
mkdir -p "$HOME_DIR/rules"
ln -s /etc/hosts "$HOME_DIR/rules/demo.md"
run_apply
[ "$status" = 1 ]; check $? "9 foreign symlink at an owned target: apply exits 1"
grep -q "^CONFLICT: $HOME_DIR/rules/demo.md" "$ERR"; check $? "9 foreign symlink at an owned target is a CONFLICT"
[ "$(readlink "$HOME_DIR/rules/demo.md")" = /etc/hosts ]; check $? "9 foreign symlink at an owned target is left alone"

fresh_home
mkdir -p "$HOME_DIR/agents" "$HOME_DIR/skills"
ln -s "$FIX/claude/rules/demo.md" "$HOME_DIR/agents/demo.md"
ln -s "$FIX/claude" "$HOME_DIR/skills/demo"
run_apply
[ "$status" = 0 ]; check $? "10 links elsewhere under the repo: apply exits 0"
! grep -q '^CONFLICT' "$ERR"; check $? "10 links elsewhere under the repo are no CONFLICT"
all_linked "10 relinking"
grep -q "^  link: $HOME_DIR/agents/demo.md -> $FIX/claude/agents/demo.md$" "$OUT"; check $? "10 the relinked file is reported"
grep -q "^  link: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT"; check $? "10 the relinked directory is reported"
[ ! -e "$FIX/claude/demo" ]; check $? "10 no demo entry lands inside the directory the link pointed at"
[ ! -L "$FIX/claude/demo" ]; check $? "10 no link lands inside the directory the link pointed at"

fresh_home
mkdir -p "$HOME_DIR/agents" "$HOME_DIR/rules"
ln -s ../../repo/claude/agents/demo.md "$HOME_DIR/agents/demo.md"
ln -s ../../repo/claude/agents/demo.md "$HOME_DIR/rules/demo.md"
run_apply
[ "$status" = 0 ]; check $? "11 relative link into the repo: apply exits 0"
! grep -q '^CONFLICT' "$ERR"; check $? "11 relative link into the repo is no CONFLICT"
! grep -q '^  foreign:' "$OUT"; check $? "11 relative link into the repo is not foreign"
grep -q "^  ok: $HOME_DIR/agents/demo.md -> $FIX/claude/agents/demo.md$" "$OUT"; check $? "11 an exact relative link is ok"
[ "$(readlink "$HOME_DIR/agents/demo.md")" = ../../repo/claude/agents/demo.md ]; check $? "11 an exact relative link is left as written"
grep -q "^  link: $HOME_DIR/rules/demo.md -> $FIX/claude/rules/demo.md$" "$OUT"; check $? "11 a relative link to another repo path is relinked"
links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md"; check $? "11 the relinked rule points at its source"

fresh_home
mkdir -p "$HOME_DIR/agents" "$HOME_DIR/hooks"
ln -s ../../repo/./claude/agents/demo.md "$HOME_DIR/agents/demo.md"
ln -s "$FIX//claude/hooks//demo.py" "$HOME_DIR/hooks/demo.py"
run_apply
[ "$status" = 0 ]; check $? "12 link targets with a dot segment or doubled slash: apply exits 0"
! grep -q '^CONFLICT' "$ERR"; check $? "12 link targets with a dot segment or doubled slash are no CONFLICT"
! grep -q '^  foreign:' "$OUT"; check $? "12 link targets with a dot segment or doubled slash are not foreign"
grep -q "^  ok: $HOME_DIR/agents/demo.md -> $FIX/claude/agents/demo.md$" "$OUT"; check $? "12 a link target with a dot segment is ok"
grep -q "^  ok: $HOME_DIR/hooks/demo.py -> $FIX/claude/hooks/demo.py$" "$OUT"; check $? "12 a link target with a doubled slash is ok"
[ "$(readlink "$HOME_DIR/agents/demo.md")" = ../../repo/./claude/agents/demo.md ]; check $? "12 a link target with a dot segment is left as written"
[ "$(readlink "$HOME_DIR/hooks/demo.py")" = "$FIX//claude/hooks//demo.py" ]; check $? "12 a link target with a doubled slash is left as written"

fresh_home
run_apply
echo "other" > "$HOME_DIR/skills/other.md"
run_apply
[ "$status" = 0 ]; check $? "13 foreign regular file: apply exits 0"
grep -q "^  foreign: $HOME_DIR/skills/other.md$" "$OUT"; check $? "13 foreign regular file is reported"
run_apply --check
[ "$status" = 1 ]; check $? "13 foreign regular file fails check"
[ -f "$HOME_DIR/skills/other.md" ]; check $? "13 foreign regular file is left alone"

fresh_home
run_apply
ln -s /etc/hosts "$HOME_DIR/hooks/x.py"
run_apply
[ "$status" = 0 ]; check $? "14 foreign symlink in an owned dir: apply exits 0"
[ "$(readlink "$HOME_DIR/hooks/x.py")" = /etc/hosts ]; check $? "14 foreign symlink in an owned dir is left alone"
grep -q "^  foreign: $HOME_DIR/hooks/x.py$" "$OUT"; check $? "14 foreign symlink in an owned dir is reported"
! grep -Eq '^  (link|prune|adopt): .*x\.py' "$OUT"; check $? "14 foreign symlink in an owned dir is neither linked, pruned nor adopted"

fresh_home
run_apply
ln -s "$FIX/claude/rules/demo.md" "$HOME_DIR/agents/other.md"
run_apply
[ "$status" = 0 ]; check $? "15 link to another repo path in an owned dir: apply exits 0"
grep -q "^  foreign: $HOME_DIR/agents/other.md$" "$OUT"; check $? "15 link to another repo path in an owned dir is foreign"
run_apply --check
[ "$status" = 1 ]; check $? "15 link to another repo path in an owned dir fails check"
[ "$(readlink "$HOME_DIR/agents/other.md")" = "$FIX/claude/rules/demo.md" ]; check $? "15 link to another repo path in an owned dir is left alone"

fresh_home
run_apply
[ "$status" = 0 ]; check $? "16 agents skills link: apply exits 0"
grep -q "^  link: $AGENTS_DIR/demo -> $FIX/claude/skills/demo$" "$OUT"; check $? "16 agents skills link is reported"
links_to "$AGENTS_DIR/demo" "$FIX/claude/skills/demo"; check $? "16 agents skills link is created"

cp "$CODEX_DIR/AGENTS.md" "$WORK/agents.before"
run_apply
[ "$status" = 0 ]; check $? "17 second apply exits 0"
grep -q "^  ok: $CODEX_DIR/AGENTS.md$" "$OUT"; check $? "17 second apply reports AGENTS.md ok"
! grep -q '^  generate:' "$OUT"; check $? "17 second apply generates no AGENTS.md"
cmp -s "$WORK/agents.before" "$CODEX_DIR/AGENTS.md"; check $? "17 second apply leaves AGENTS.md byte-identical"

echo "plain rule v2" > "$FIX/claude/rules/plain.md"
printf '%s\n' '<!-- generated by ai-config apply.sh from claude/CLAUDE.md and claude/rules; edit those, not this file -->' \
  '' 'claude' '' '# Demo' 'rule' '' 'plain rule v2' > "$WORK/agents.v2"
run_apply
[ "$status" = 0 ]; check $? "18 editing a rule: apply exits 0"
grep -q "^  generate: $CODEX_DIR/AGENTS.md$" "$OUT"; check $? "18 editing a rule regenerates AGENTS.md"
cmp -s "$WORK/agents.v2" "$CODEX_DIR/AGENTS.md"; check $? "18 the regenerated AGENTS.md carries the new content"
echo "plain rule" > "$FIX/claude/rules/plain.md"

fresh_home
echo "mine" > "$CODEX_DIR/AGENTS.md"
run_apply
[ "$status" = 1 ]; check $? "19 foreign AGENTS.md without the marker: apply exits 1"
grep -q "^CONFLICT: $CODEX_DIR/AGENTS.md (not generated by apply.sh)$" "$ERR"; check $? "19 foreign AGENTS.md without the marker is a CONFLICT"
! grep -q '^Applied\.' "$OUT"; check $? "19 foreign AGENTS.md without the marker: apply prints no Applied line"
[ ! -L "$CODEX_DIR/AGENTS.md" ]; check $? "19 foreign AGENTS.md without the marker is left unlinked"
[ "$(cat "$CODEX_DIR/AGENTS.md")" = "mine" ]; check $? "19 foreign AGENTS.md without the marker keeps its content"
[ "$(ls -A "$CODEX_DIR")" = "AGENTS.md" ]; check $? "19 nothing else lands in CODEX_HOME"

fresh_home
cp "$AGENTS_MD" "$WORK/agents.real"
ln -s "$WORK/agents.real" "$CODEX_DIR/AGENTS.md"
run_apply
[ "$status" = 1 ]; check $? "20 symlinked AGENTS.md: apply exits 1"
grep -q "^CONFLICT: $CODEX_DIR/AGENTS.md (not generated by apply.sh)$" "$ERR"; check $? "20 symlinked AGENTS.md is a CONFLICT even when its content matches"
[ "$(readlink "$CODEX_DIR/AGENTS.md")" = "$WORK/agents.real" ]; check $? "20 symlinked AGENTS.md is left alone"
cmp -s "$AGENTS_MD" "$WORK/agents.real"; check $? "20 the file behind the symlinked AGENTS.md is left alone"

fresh_home
rmdir "$CODEX_DIR"
run_apply
[ "$status" = 0 ]; check $? "21 absent CODEX_HOME: apply exits 0"
grep -q "^  skip: $CODEX_DIR absent$" "$OUT"; check $? "21 absent CODEX_HOME is skipped"
run_apply --check
[ "$status" = 0 ]; check $? "21 absent CODEX_HOME passes check"
[ ! -e "$CODEX_DIR" ]; check $? "21 absent CODEX_HOME is not created"

fresh_home
run_apply
rm "$CODEX_DIR/AGENTS.md"
run_apply --check
[ "$status" = 1 ]; check $? "22 check with AGENTS.md pending exits 1"
grep -q "^  generate: $CODEX_DIR/AGENTS.md$" "$OUT"; check $? "22 check with AGENTS.md pending reports the pending generate"
[ -z "$(ls -A "$CODEX_DIR")" ]; check $? "22 check with AGENTS.md pending writes nothing"

run_apply
[ "$status" = 0 ]; check $? "23 apply after the pending generate exits 0"
run_apply --check
[ "$status" = 0 ]; check $? "23 check after apply exits 0"
cmp -s "$AGENTS_MD" "$CODEX_DIR/AGENTS.md"; check $? "23 the regenerated AGENTS.md matches the rendered content"

fresh_home
run_apply
echo "other" > "$AGENTS_DIR/other.md"
run_apply
[ "$status" = 0 ]; check $? "24 foreign file in the agents skills dir: apply exits 0"
grep -q "^  foreign: $AGENTS_DIR/other.md$" "$OUT"; check $? "24 foreign file in the agents skills dir is reported"
run_apply --check
[ "$status" = 1 ]; check $? "24 foreign file in the agents skills dir fails check"
[ -f "$AGENTS_DIR/other.md" ]; check $? "24 foreign file in the agents skills dir is left alone"

fresh_home
run_apply
[ "$status" = 0 ]; check $? "25 fresh apply with a rule set present exits 0"
[ "$(ls "$HOME_DIR/rules")" = "$(printf 'demo.md\nplain.md')" ]; check $? "25 global targets never include a rule-set file such as code-style.md"
! grep -q 'code-style' "$OUT"; check $? "25 no rule-set file is named on stdout"
! grep -q 'code-style' "$ERR"; check $? "25 no rule-set file is named on stderr"
! grep -q 'typescript rule' "$CODEX_DIR/AGENTS.md"; check $? "25 no rule-set rule reaches AGENTS.md"

fresh_home
run_apply
rm -r "$FIX/claude/skills/demo"
run_apply
[ "$status" = 0 ]; check $? "26 dangling owned links: apply exits 0"
grep -q "^  prune: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT"; check $? "26 the prune in the claude skills dir is reported"
[ ! -L "$HOME_DIR/skills/demo" ]; check $? "26 the dangling link in the claude skills dir is pruned"
[ ! -e "$HOME_DIR/skills/demo" ]; check $? "26 the pruned claude skills link is gone"
grep -q "^  prune: $AGENTS_DIR/demo -> $FIX/claude/skills/demo$" "$OUT"; check $? "26 the prune in the agents skills dir is reported"
[ ! -L "$AGENTS_DIR/demo" ]; check $? "26 the dangling link in the agents skills dir is pruned"
[ ! -e "$AGENTS_DIR/demo" ]; check $? "26 the pruned agents skills link is gone"

fresh_home
mkdir -p "$HOME_DIR"
printf '%s\n' '{"attribution": {"commit": "x"}}' > "$HOME_DIR/settings.json"
run_apply
[ "$status" = 0 ]; check $? "27 pre-existing attribution: apply exits 0"
python3 -c '
import json, sys
text = open(sys.argv[1]).read()
doc = json.loads(text)
assert list(doc) == ["attribution", "hooks", "permissions"]
assert doc["attribution"] == {"commit": "x"}
assert "  \"attribution\": {\n    \"commit\": \"x\"\n  },\n" in text
' "$HOME_DIR/settings.json"
check $? "27 pre-existing attribution survives apply and is not completed"

fresh_home
run_apply
[ "$status" = 0 ]; check $? "28 apply before a default is removed exits 0"
python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
del doc["attribution"]
open(sys.argv[1], "w").write(json.dumps(doc, indent=2) + "\n")
' "$HOME_DIR/settings.json"
cp "$HOME_DIR/settings.json" "$WORK/settings.before"
run_apply --check
[ "$status" = 1 ]; check $? "28 check with a missing default exits 1"
grep -q '^  settings: would change$' "$OUT"; check $? "28 check reports a missing default as would change"
cmp -s "$WORK/settings.before" "$HOME_DIR/settings.json"; check $? "28 check writes no settings.json"

fresh_home
mkdir -p "$HOME_DIR"
printf '%s\n' '{"permissions": {"allow": ["Bash(ls:*)"]}}' > "$HOME_DIR/settings.json"
run_apply
[ "$status" = 0 ]; check $? "29 a user allow entry: apply exits 0"
python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
assert doc["permissions"]["allow"] == [
    "Bash(ls:*)", "Bash(git commit:*)", "Bash(rm:*)", "Bash(find:*)", "Bash(mv:*)"
]
assert doc["permissions"]["ask"] == ["Bash(git push:*)"]
' "$HOME_DIR/settings.json"
check $? "29 a user allow entry survives apply and the manifest entries are appended"

fresh_home
run_apply
[ "$status" = 0 ]; check $? "30 fresh apply with a local bin dir off PATH exits 0"
grep -q "^  link: $BIN_DIR/second-opinion-codex -> $FIX/bin/second-opinion-codex$" "$OUT"; check $? "30 the second-opinion link is reported"
links_to "$BIN_DIR/second-opinion-codex" "$FIX/bin/second-opinion-codex"; check $? "30 the second-opinion script is linked into the local bin dir"
[ "$(grep -c '^  warn: ' "$OUT")" = 1 ]; check $? "30 the local bin dir off PATH warns once"
grep -q "^  warn: $BIN_DIR is not on PATH$" "$OUT"; check $? "30 the warn line names the local bin dir"

RUN_PATH="$BIN_DIR:$PATH"
run_apply
[ "$status" = 0 ]; check $? "31 a local bin dir on PATH: apply exits 0"
run_apply --check
RUN_PATH="$PATH"
[ "$status" = 0 ]; check $? "31 a local bin dir on PATH passes check"
grep -q "^  ok: $BIN_DIR/second-opinion-codex -> $FIX/bin/second-opinion-codex$" "$OUT"; check $? "31 a local bin dir on PATH is reported ok"
! grep -q '^  warn: ' "$OUT"; check $? "31 a local bin dir on PATH prints no warn line"

fresh_home
run_apply
ln -s /nonexistent/x "$BIN_DIR/other"
rm "$FIX/bin/second-opinion-codex"
run_apply
[ "$status" = 0 ]; check $? "32 a dangling second-opinion-codex link: apply exits 0"
printf '%s\n' '#!/bin/bash' 'exit 0' > "$FIX/bin/second-opinion-codex"
grep -q "^  prune: $BIN_DIR/second-opinion-codex -> $FIX/bin/second-opinion-codex$" "$OUT"; check $? "32 the prune of the second-opinion link is reported"
[ ! -L "$BIN_DIR/second-opinion-codex" ]; check $? "32 the dangling second-opinion link is pruned"
[ ! -e "$BIN_DIR/second-opinion-codex" ]; check $? "32 nothing is left where the second-opinion link was"
[ -L "$BIN_DIR/other" ]; check $? "32 a link the repo does not own is left alone"
! grep -q "^  prune: $BIN_DIR/other" "$OUT"; check $? "32 a link the repo does not own is not reported pruned"

summary
