#!/bin/bash
set -u

HERE="$(cd "$(dirname "$0")" && pwd -P)"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/ai-config-test.XXXXXX")" || exit 1
WORK="$(cd "$WORK" && pwd -P)" || exit 1
trap 'rm -rf "$WORK"' EXIT

FIX="$WORK/repo"
mkdir -p "$FIX/claude/skills/demo" "$FIX/claude/agents" "$FIX/claude/rules" "$FIX/claude/hooks" "$FIX/scripts"
mkdir -p "$FIX/claude/rulesets/typescript" "$FIX/lib" "$FIX/bin"
cp "$HERE/../apply.sh" "$FIX/apply.sh"
cp "$HERE/../lib/links.sh" "$FIX/lib/links.sh"
cp "$HERE/../scripts/merge_settings.py" "$FIX/scripts/merge_settings.py"
cp "$HERE/../scripts/render_agents_md.py" "$FIX/scripts/render_agents_md.py"
echo "claude" > "$FIX/claude/CLAUDE.md"
echo "skill" > "$FIX/claude/skills/demo/SKILL.md"
echo "agent" > "$FIX/claude/agents/demo.md"
printf '%s\n' '---' 'paths: ["**/*.ts"]' '---' '# Demo' 'rule' > "$FIX/claude/rules/demo.md"
echo "plain rule" > "$FIX/claude/rules/plain.md"
printf '%s\n' '---' 'paths: ["**/*.ts"]' '---' '# Code style' 'typescript rule' > "$FIX/claude/rulesets/typescript/code-style.md"
echo "print('hook')" > "$FIX/claude/hooks/demo.py"
printf '%s\n' '#!/bin/bash' 'exit 0' > "$FIX/bin/second-opinion-codex"
printf '%s\n' '{"hooks": {"PreToolUse": [{"matcher": "Bash", "script": "demo.py", "timeout": 10}]},' \
  ' "defaults": {"attribution": {"commit": "", "pr": "", "sessionUrl": false},' \
  '  "permissions.allow": ["Bash(git commit:*)", "Bash(rm:*)", "Bash(find:*)", "Bash(mv:*)"],' \
  '  "permissions.ask": ["Bash(git push:*)"]}}' > "$FIX/claude/settings.json"

AGENTS_MD="$WORK/agents.expected"
printf '%s\n' '<!-- generated by ai-config apply.sh from claude/CLAUDE.md and claude/rules; edit those, not this file -->' \
  '' 'claude' '' '# Demo' 'rule' '' 'plain rule' > "$AGENTS_MD"

pass=0
fail=0
check() {
  if [ "$1" = 0 ]; then echo "PASS $2"; pass=$((pass + 1)); else echo "FAIL $2"; fail=$((fail + 1)); fi
}

homes=0
fresh_home() {
  homes=$((homes + 1))
  HOME_DIR="$WORK/home$homes"
  AGENTS_DIR="$WORK/agents$homes"
  CODEX_DIR="$WORK/codex$homes"
  BIN_DIR="$WORK/bin$homes"
  mkdir -p "$CODEX_DIR"
}

OUT="$WORK/out"
ERR="$WORK/err"
RUN_PATH="$PATH"
run_apply() {
  CLAUDE_CONFIG_DIR="$HOME_DIR" AGENTS_SKILLS_DIR="$AGENTS_DIR" CODEX_HOME="$CODEX_DIR" \
    CLAUDE_LOCAL_BIN="$BIN_DIR" PATH="$RUN_PATH" \
    /bin/bash "$FIX/apply.sh" "$@" >"$OUT" 2>"$ERR"
  status=$?
}

links_to() { [ -L "$1" ] && [ "$(readlink "$1")" = "$2" ]; }

all_linked() {
  links_to "$HOME_DIR/CLAUDE.md" "$FIX/claude/CLAUDE.md" \
    && links_to "$HOME_DIR/skills/demo" "$FIX/claude/skills/demo" \
    && links_to "$HOME_DIR/agents/demo.md" "$FIX/claude/agents/demo.md" \
    && links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md" \
    && links_to "$HOME_DIR/hooks/demo.py" "$FIX/claude/hooks/demo.py" \
    && links_to "$AGENTS_DIR/demo" "$FIX/claude/skills/demo" \
    && links_to "$BIN_DIR/second-opinion-codex" "$FIX/bin/second-opinion-codex"
}

fresh_home
run_apply --check
[ "$status" = 1 ] && [ ! -e "$HOME_DIR" ] && [ ! -L "$HOME_DIR" ] \
  && [ ! -e "$AGENTS_DIR" ] && [ ! -e "$BIN_DIR" ] && [ -z "$(ls -A "$CODEX_DIR")" ]
check $? "1 check on a nonexistent target exits 1 and leaves it absent"

run_apply
[ "$status" = 0 ] && all_linked \
  && grep -q '^Applied\. Restart Claude Code sessions to pick up changes\.$' "$OUT" \
  && python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
group = doc["hooks"]["PreToolUse"][0]
assert group["matcher"] == "Bash"
assert group["hooks"] == [{"type": "command", "command": "python3 " + sys.argv[2] + "/hooks/demo.py", "timeout": 10}]
assert doc["attribution"] == {"commit": "", "pr": "", "sessionUrl": False}
assert doc["permissions"] == {
    "allow": ["Bash(git commit:*)", "Bash(rm:*)", "Bash(find:*)", "Bash(mv:*)"],
    "ask": ["Bash(git push:*)"],
}
assert list(doc) == ["hooks", "attribution", "permissions"]
' "$HOME_DIR/settings.json" "$HOME_DIR"
check $? "2 fresh apply links every target, writes the demo hook and the defaults and prints Applied"

cp "$HOME_DIR/settings.json" "$WORK/settings.before"
run_apply
[ "$status" = 0 ] && ! grep -Eq '^  (link|adopt|prune|foreign):' "$OUT" \
  && [ "$(grep -c '^  ok: ' "$OUT")" = 9 ] \
  && grep -q "^  ok: $HOME_DIR/CLAUDE.md -> $FIX/claude/CLAUDE.md$" "$OUT" \
  && grep -q "^  ok: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT" \
  && cmp -s "$WORK/settings.before" "$HOME_DIR/settings.json"
check $? "3 second apply changes nothing and prints ok for every target"

run_apply --check
[ "$status" = 0 ]
check $? "4 check after apply exits 0"

fresh_home
mkdir -p "$HOME_DIR/agents"
echo "different" > "$HOME_DIR/agents/demo.md"
run_apply
[ "$status" = 1 ] && grep -q "^CONFLICT: $HOME_DIR/agents/demo.md" "$ERR" && ! grep -q '^Applied\.' "$OUT" \
  && [ ! -L "$HOME_DIR/agents/demo.md" ] && [ "$(cat "$HOME_DIR/agents/demo.md")" = "different" ] \
  && links_to "$HOME_DIR/CLAUDE.md" "$FIX/claude/CLAUDE.md" \
  && links_to "$HOME_DIR/skills/demo" "$FIX/claude/skills/demo" \
  && links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md" \
  && links_to "$HOME_DIR/hooks/demo.py" "$FIX/claude/hooks/demo.py"
check $? "5 differing regular file is a CONFLICT without Applied and the rest is still linked"

fresh_home
mkdir -p "$HOME_DIR/rules"
cp "$FIX/claude/rules/demo.md" "$HOME_DIR/rules/demo.md"
run_apply
[ "$status" = 0 ] && grep -q "^  adopt: $HOME_DIR/rules/demo.md -> $FIX/claude/rules/demo.md$" "$OUT" \
  && links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md"
check $? "6 identical regular file is adopted"

fresh_home
mkdir -p "$HOME_DIR/skills"
cp -R "$FIX/claude/skills/demo" "$HOME_DIR/skills/demo"
run_apply
[ "$status" = 0 ] && grep -q "^  adopt: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT" \
  && links_to "$HOME_DIR/skills/demo" "$FIX/claude/skills/demo" \
  && [ ! -e "$FIX/claude/skills/demo/demo" ] && [ ! -L "$FIX/claude/skills/demo/demo" ] \
  && [ "$(cat "$FIX/claude/skills/demo/SKILL.md")" = "skill" ]
check $? "7 identical directory is adopted with nothing nested"

fresh_home
mkdir -p "$HOME_DIR/skills"
echo "x" > "$HOME_DIR/skills/demo"
run_apply
[ "$status" = 1 ] && grep -q "^CONFLICT: $HOME_DIR/skills/demo" "$ERR" \
  && [ ! -L "$HOME_DIR/skills/demo" ] && [ "$(cat "$HOME_DIR/skills/demo")" = "x" ]
check $? "8 regular file at a skill target is a CONFLICT"

fresh_home
mkdir -p "$HOME_DIR/rules"
ln -s /etc/hosts "$HOME_DIR/rules/demo.md"
run_apply
[ "$status" = 1 ] && grep -q "^CONFLICT: $HOME_DIR/rules/demo.md" "$ERR" \
  && [ "$(readlink "$HOME_DIR/rules/demo.md")" = /etc/hosts ]
check $? "9 foreign symlink at an owned target is a CONFLICT and left alone"

fresh_home
mkdir -p "$HOME_DIR/agents" "$HOME_DIR/skills"
ln -s "$FIX/claude/rules/demo.md" "$HOME_DIR/agents/demo.md"
ln -s "$FIX/claude" "$HOME_DIR/skills/demo"
run_apply
[ "$status" = 0 ] && ! grep -q '^CONFLICT' "$ERR" && all_linked \
  && grep -q "^  link: $HOME_DIR/agents/demo.md -> $FIX/claude/agents/demo.md$" "$OUT" \
  && grep -q "^  link: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT" \
  && [ ! -e "$FIX/claude/demo" ] && [ ! -L "$FIX/claude/demo" ]
check $? "10 links elsewhere under the repo are relinked for a file and a directory"

fresh_home
mkdir -p "$HOME_DIR/agents" "$HOME_DIR/rules"
ln -s ../../repo/claude/agents/demo.md "$HOME_DIR/agents/demo.md"
ln -s ../../repo/claude/agents/demo.md "$HOME_DIR/rules/demo.md"
run_apply
[ "$status" = 0 ] && ! grep -q '^CONFLICT' "$ERR" && ! grep -q '^  foreign:' "$OUT" \
  && grep -q "^  ok: $HOME_DIR/agents/demo.md -> $FIX/claude/agents/demo.md$" "$OUT" \
  && [ "$(readlink "$HOME_DIR/agents/demo.md")" = ../../repo/claude/agents/demo.md ] \
  && grep -q "^  link: $HOME_DIR/rules/demo.md -> $FIX/claude/rules/demo.md$" "$OUT" \
  && links_to "$HOME_DIR/rules/demo.md" "$FIX/claude/rules/demo.md"
check $? "11 relative link into the repo is ok when exact and relinked otherwise"

fresh_home
mkdir -p "$HOME_DIR/agents" "$HOME_DIR/hooks"
ln -s ../../repo/./claude/agents/demo.md "$HOME_DIR/agents/demo.md"
ln -s "$FIX//claude/hooks//demo.py" "$HOME_DIR/hooks/demo.py"
run_apply
[ "$status" = 0 ] && ! grep -q '^CONFLICT' "$ERR" && ! grep -q '^  foreign:' "$OUT" \
  && grep -q "^  ok: $HOME_DIR/agents/demo.md -> $FIX/claude/agents/demo.md$" "$OUT" \
  && grep -q "^  ok: $HOME_DIR/hooks/demo.py -> $FIX/claude/hooks/demo.py$" "$OUT" \
  && [ "$(readlink "$HOME_DIR/agents/demo.md")" = ../../repo/./claude/agents/demo.md ] \
  && [ "$(readlink "$HOME_DIR/hooks/demo.py")" = "$FIX//claude/hooks//demo.py" ]
check $? "12 link targets with a dot segment or doubled slash are ok"

fresh_home
run_apply
echo "other" > "$HOME_DIR/skills/other.md"
run_apply
apply_status=$status
grep -q "^  foreign: $HOME_DIR/skills/other.md$" "$OUT"
foreign_reported=$?
run_apply --check
[ "$apply_status" = 0 ] && [ "$foreign_reported" = 0 ] && [ "$status" = 1 ] && [ -f "$HOME_DIR/skills/other.md" ]
check $? "13 foreign regular file is reported and fails check"

fresh_home
run_apply
ln -s /etc/hosts "$HOME_DIR/hooks/x.py"
run_apply
[ "$status" = 0 ] && [ "$(readlink "$HOME_DIR/hooks/x.py")" = /etc/hosts ] \
  && grep -q "^  foreign: $HOME_DIR/hooks/x.py$" "$OUT" && ! grep -Eq '^  (link|prune|adopt): .*x\.py' "$OUT"
check $? "14 foreign symlink in an owned dir is left alone and reported"

fresh_home
run_apply
ln -s "$FIX/claude/rules/demo.md" "$HOME_DIR/agents/other.md"
run_apply
apply_status=$status
grep -q "^  foreign: $HOME_DIR/agents/other.md$" "$OUT"
foreign_reported=$?
run_apply --check
[ "$apply_status" = 0 ] && [ "$foreign_reported" = 0 ] && [ "$status" = 1 ] \
  && [ "$(readlink "$HOME_DIR/agents/other.md")" = "$FIX/claude/rules/demo.md" ]
check $? "15 link to another repo path in an owned dir is foreign and fails check"

fresh_home
run_apply
[ "$status" = 0 ] && grep -q "^  link: $AGENTS_DIR/demo -> $FIX/claude/skills/demo$" "$OUT" \
  && links_to "$AGENTS_DIR/demo" "$FIX/claude/skills/demo"
check $? "16 agents skills link is created and reported"

[ "$status" = 0 ] && grep -q "^  generate: $CODEX_DIR/AGENTS.md$" "$OUT" \
  && [ -f "$CODEX_DIR/AGENTS.md" ] && [ ! -L "$CODEX_DIR/AGENTS.md" ] \
  && cmp -s "$AGENTS_MD" "$CODEX_DIR/AGENTS.md" && ! grep -q '^paths:' "$CODEX_DIR/AGENTS.md"
check $? "17 AGENTS.md is generated with marker, CLAUDE.md text and rule bodies without frontmatter"

cp "$CODEX_DIR/AGENTS.md" "$WORK/agents.before"
run_apply
[ "$status" = 0 ] && grep -q "^  ok: $CODEX_DIR/AGENTS.md$" "$OUT" && ! grep -q '^  generate:' "$OUT" \
  && cmp -s "$WORK/agents.before" "$CODEX_DIR/AGENTS.md"
check $? "18 second apply reports AGENTS.md ok and leaves it byte-identical"

echo "plain rule v2" > "$FIX/claude/rules/plain.md"
printf '%s\n' '<!-- generated by ai-config apply.sh from claude/CLAUDE.md and claude/rules; edit those, not this file -->' \
  '' 'claude' '' '# Demo' 'rule' '' 'plain rule v2' > "$WORK/agents.v2"
run_apply
[ "$status" = 0 ] && grep -q "^  generate: $CODEX_DIR/AGENTS.md$" "$OUT" \
  && cmp -s "$WORK/agents.v2" "$CODEX_DIR/AGENTS.md"
check $? "19 editing a rule regenerates AGENTS.md with the new content"
echo "plain rule" > "$FIX/claude/rules/plain.md"

fresh_home
echo "mine" > "$CODEX_DIR/AGENTS.md"
run_apply
[ "$status" = 1 ] && grep -q "^CONFLICT: $CODEX_DIR/AGENTS.md (not generated by apply.sh)$" "$ERR" \
  && ! grep -q '^Applied\.' "$OUT" && [ ! -L "$CODEX_DIR/AGENTS.md" ] \
  && [ "$(cat "$CODEX_DIR/AGENTS.md")" = "mine" ] && [ "$(ls -A "$CODEX_DIR")" = "AGENTS.md" ]
check $? "20 foreign AGENTS.md without the marker is a CONFLICT and untouched"

fresh_home
cp "$AGENTS_MD" "$WORK/agents.real"
ln -s "$WORK/agents.real" "$CODEX_DIR/AGENTS.md"
run_apply
[ "$status" = 1 ] && grep -q "^CONFLICT: $CODEX_DIR/AGENTS.md (not generated by apply.sh)$" "$ERR" \
  && [ "$(readlink "$CODEX_DIR/AGENTS.md")" = "$WORK/agents.real" ] && cmp -s "$AGENTS_MD" "$WORK/agents.real"
check $? "21 symlinked AGENTS.md is a CONFLICT and left alone even when its content matches"

fresh_home
rmdir "$CODEX_DIR"
run_apply
apply_status=$status
grep -q "^  skip: $CODEX_DIR absent$" "$OUT"
skip_reported=$?
run_apply --check
[ "$apply_status" = 0 ] && [ "$skip_reported" = 0 ] && [ "$status" = 0 ] && [ ! -e "$CODEX_DIR" ]
check $? "22 absent CODEX_HOME is skipped, nothing is created and check passes"

fresh_home
run_apply
rm "$CODEX_DIR/AGENTS.md"
run_apply --check
[ "$status" = 1 ] && grep -q "^  generate: $CODEX_DIR/AGENTS.md$" "$OUT" && [ -z "$(ls -A "$CODEX_DIR")" ]
check $? "23 check with AGENTS.md pending exits 1 and writes nothing"

run_apply
apply_status=$status
run_apply --check
[ "$apply_status" = 0 ] && [ "$status" = 0 ] && cmp -s "$AGENTS_MD" "$CODEX_DIR/AGENTS.md"
check $? "24 check after apply exits 0"

fresh_home
run_apply
echo "other" > "$AGENTS_DIR/other.md"
run_apply
apply_status=$status
grep -q "^  foreign: $AGENTS_DIR/other.md$" "$OUT"
foreign_reported=$?
run_apply --check
[ "$apply_status" = 0 ] && [ "$foreign_reported" = 0 ] && [ "$status" = 1 ] && [ -f "$AGENTS_DIR/other.md" ]
check $? "25 foreign file in the agents skills dir is reported and fails check"

fresh_home
run_apply
[ "$status" = 0 ] && [ "$(ls "$HOME_DIR/rules")" = "$(printf 'demo.md\nplain.md')" ] \
  && ! grep -q 'code-style' "$OUT" && ! grep -q 'code-style' "$ERR" \
  && ! grep -q 'typescript rule' "$CODEX_DIR/AGENTS.md"
check $? "26 global targets never include a rule-set file such as code-style.md"

fresh_home
run_apply
rm -r "$FIX/claude/skills/demo"
run_apply
[ "$status" = 0 ] && grep -q "^  prune: $HOME_DIR/skills/demo -> $FIX/claude/skills/demo$" "$OUT" \
  && [ ! -L "$HOME_DIR/skills/demo" ] && [ ! -e "$HOME_DIR/skills/demo" ] \
  && grep -q "^  prune: $AGENTS_DIR/demo -> $FIX/claude/skills/demo$" "$OUT" \
  && [ ! -L "$AGENTS_DIR/demo" ] && [ ! -e "$AGENTS_DIR/demo" ]
check $? "27 dangling owned links are pruned in both skills dirs"

fresh_home
mkdir -p "$HOME_DIR"
printf '%s\n' '{"attribution": {"commit": "x"}}' > "$HOME_DIR/settings.json"
run_apply
[ "$status" = 0 ] && python3 -c '
import json, sys
text = open(sys.argv[1]).read()
doc = json.loads(text)
assert list(doc) == ["attribution", "hooks", "permissions"]
assert doc["attribution"] == {"commit": "x"}
assert "  \"attribution\": {\n    \"commit\": \"x\"\n  },\n" in text
' "$HOME_DIR/settings.json"
check $? "28 pre-existing attribution survives apply and is not completed"

fresh_home
run_apply
apply_status=$status
python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
del doc["attribution"]
open(sys.argv[1], "w").write(json.dumps(doc, indent=2) + "\n")
' "$HOME_DIR/settings.json"
cp "$HOME_DIR/settings.json" "$WORK/settings.before"
run_apply --check
[ "$apply_status" = 0 ] && [ "$status" = 1 ] && grep -q '^  settings: would change$' "$OUT" \
  && cmp -s "$WORK/settings.before" "$HOME_DIR/settings.json"
check $? "29 check reports a missing default as would change and writes nothing"

fresh_home
mkdir -p "$HOME_DIR"
printf '%s\n' '{"permissions": {"allow": ["Bash(ls:*)"]}}' > "$HOME_DIR/settings.json"
run_apply
[ "$status" = 0 ] && python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
assert doc["permissions"]["allow"] == [
    "Bash(ls:*)", "Bash(git commit:*)", "Bash(rm:*)", "Bash(find:*)", "Bash(mv:*)"
]
assert doc["permissions"]["ask"] == ["Bash(git push:*)"]
' "$HOME_DIR/settings.json"
check $? "30 a user allow entry survives apply and the manifest entries are appended"

fresh_home
run_apply
[ "$status" = 0 ] && grep -q "^  link: $BIN_DIR/second-opinion-codex -> $FIX/bin/second-opinion-codex$" "$OUT" \
  && links_to "$BIN_DIR/second-opinion-codex" "$FIX/bin/second-opinion-codex" \
  && [ "$(grep -c '^  warn: ' "$OUT")" = 1 ] \
  && grep -q "^  warn: $BIN_DIR is not on PATH$" "$OUT"
check $? "31 fresh apply links the second-opinion script into the local bin dir and warns once that the dir is not on PATH"

RUN_PATH="$BIN_DIR:$PATH"
run_apply
run_status=$status
run_apply --check
RUN_PATH="$PATH"
[ "$run_status" = 0 ] && [ "$status" = 0 ] \
  && grep -q "^  ok: $BIN_DIR/second-opinion-codex -> $FIX/bin/second-opinion-codex$" "$OUT" \
  && ! grep -q '^  warn: ' "$OUT"
check $? "32 a local bin dir on PATH is reported ok without a warn line and passes check"

fresh_home
run_apply
ln -s /nonexistent/x "$BIN_DIR/other"
rm "$FIX/bin/second-opinion-codex"
run_apply
prune_status=$status
printf '%s\n' '#!/bin/bash' 'exit 0' > "$FIX/bin/second-opinion-codex"
[ "$prune_status" = 0 ] && grep -q "^  prune: $BIN_DIR/second-opinion-codex -> $FIX/bin/second-opinion-codex$" "$OUT" \
  && [ ! -L "$BIN_DIR/second-opinion-codex" ] && [ ! -e "$BIN_DIR/second-opinion-codex" ] \
  && [ -L "$BIN_DIR/other" ] && ! grep -q "^  prune: $BIN_DIR/other" "$OUT"
check $? "33 a dangling second-opinion link in the local bin dir is pruned and a link the repo does not own is left alone"

echo "PASS $pass FAIL $fail"
[ "$fail" = 0 ]
