#!/usr/bin/env python3
"""Render Codex's AGENTS.md from CLAUDE.md and the rules directory, without the claude-only blocks."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

MARKER = "<!-- generated by ai-config apply.sh from claude/CLAUDE.md and claude/rules; edit those, not this file -->"
CLAUDE_ONLY_OPEN = "<!-- claude-only -->"
CLAUDE_ONLY_CLOSE = "<!-- /claude-only -->"


class UnbalancedClaudeOnly(Exception):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--claude-md", required=True, type=Path)
    parser.add_argument("--rules-dir", required=True, type=Path)
    return parser.parse_args()


def without_claude_only(text: str, path: Path) -> str:
    kept = []
    opened_at = None
    for number, line in enumerate(text.split("\n"), start=1):
        if line == CLAUDE_ONLY_OPEN:
            if opened_at is not None:
                raise UnbalancedClaudeOnly(f"{path}:{number}: nested {CLAUDE_ONLY_OPEN}")
            opened_at = number
        elif line == CLAUDE_ONLY_CLOSE:
            if opened_at is None:
                raise UnbalancedClaudeOnly(f"{path}:{number}: {CLAUDE_ONLY_CLOSE} without {CLAUDE_ONLY_OPEN}")
            opened_at = None
        elif opened_at is None:
            kept.append(line)
    if opened_at is not None:
        raise UnbalancedClaudeOnly(f"{path}:{opened_at}: {CLAUDE_ONLY_OPEN} without {CLAUDE_ONLY_CLOSE}")
    return "\n".join(kept)


def rule_files(rules_dir: Path) -> list[Path]:
    return [rules_dir / name for name in sorted(os.listdir(rules_dir)) if name.endswith(".md")]


def read_without_claude_only(path: Path) -> str:
    return without_claude_only(path.read_text(encoding="utf-8"), path)


def render(claude_md: Path, rules_dir: Path) -> str:
    sections = [MARKER + "\n", read_without_claude_only(claude_md)]
    sections.extend(read_without_claude_only(rule) for rule in rule_files(rules_dir))
    return "\n".join(sections).rstrip("\n") + "\n"


def main() -> int:
    args = parse_args()
    try:
        rendered = render(args.claude_md, args.rules_dir)
    except (OSError, UnbalancedClaudeOnly) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    sys.stdout.buffer.write(rendered.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
