#!/usr/bin/env python3
"""Render Codex's AGENTS.md from CLAUDE.md and the rules directory."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

MARKER = "<!-- generated by ai-config apply.sh from claude/CLAUDE.md and claude/rules; edit those, not this file -->"
FENCE = "---"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--claude-md", required=True, type=Path)
    parser.add_argument("--rules-dir", required=True, type=Path)
    return parser.parse_args()


def without_frontmatter(text: str) -> str:
    lines = text.split("\n")
    if lines[0] != FENCE:
        return text
    for index in range(1, len(lines)):
        if lines[index] == FENCE:
            return "\n".join(lines[index + 1 :])
    return text


def rule_files(rules_dir: Path) -> list[Path]:
    return [rules_dir / name for name in sorted(os.listdir(rules_dir)) if name.endswith(".md")]


def render(claude_md: Path, rules_dir: Path) -> str:
    sections = [MARKER + "\n", claude_md.read_text(encoding="utf-8")]
    sections.extend(without_frontmatter(rule.read_text(encoding="utf-8")) for rule in rule_files(rules_dir))
    return "\n".join(sections).rstrip("\n") + "\n"


def main() -> int:
    args = parse_args()
    try:
        rendered = render(args.claude_md, args.rules_dir)
    except OSError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    sys.stdout.buffer.write(rendered.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
